version: '3'

services:
  web:
    build:
      context: ./
      target: web
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - api
    networks:
      - network
    env_file:
      - .env

  api:
    build:
      context: ./
      target: api
    environment:
      - PORT=3333
    ports:
      - 3333:3333
    volumes:
      - .:/app
    depends_on:
    - eventstore
    - mongodb
    networks:
      - network
    env_file:
      - .env

  eventstore:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    networks:
      - network

  mongodb:
    image: mongo:latest
    volumes:
      - type: volume
        source: mongo-volume-data
        target: /data/db
    networks:
      - network

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  mongo-volume-data:
  mongoclient-volume-data:
  
networks:
  network:
    driver: bridge
