import './global.css';
import Header from '../components/Header/Header';
import { Providers } from '../components/Providers/Providers';
import { Session } from 'next-auth';
import { AppProps } from 'next/app';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

interface MyAppProps extends AppProps {
  children: React.ReactNode;
  pageProps: {
    session: Session | null;
  };
}

export default function RootLayout({
  children,
  pageProps : {session, ...pageProps} = { session: null }, 
}: MyAppProps){
  
  return (
    <html lang="en">
      <body>
      <Providers session={session}>
        <Header/>
          {children}
      </Providers>
      </body>
    </html>
  );
}
